{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1203.0 (24.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dZona\",\"dValores\",\"dsep_setor\",\"dHora\",\"dHeadcount\",\"dCalendario\",\"dBox\",\"3_11_status_+_olpn\",\"2_04_posicoes_ocupadas_e_vazias\",\"Medidas\",\"1_06_recebimento\",\"niveis\",\"RangeStart\",\"RangeEnd\",\"auxCurva\",\"dHora_agora\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "RangeStart",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "DateTime"
          }
        ],
        "expression": "#datetime(2025, 1, 1, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "9175adcb-e63d-4bbe-9c73-838a5c828a16"
      },
      {
        "name": "RangeEnd",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "DateTime"
          }
        ],
        "expression": "#datetime(2025, 12, 31, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "9434b08b-f545-4d02-8689-77836809f2f9"
      }
    ],
    "relationships": [
      {
        "name": "c5506aaf-fa9b-2351-72c0-efd377cf446e",
        "fromColumn": "box",
        "fromTable": "3_11_status_+_olpn",
        "toColumn": "box",
        "toTable": "dBox"
      },
      {
        "name": "47fd6e44-208f-8d66-f392-085c07fbab0f",
        "fromColumn": "data_olpn",
        "fromTable": "3_11_status_+_olpn",
        "toColumn": "data",
        "toTable": "dCalendario"
      },
      {
        "name": "4443923d-c377-a048-12f6-8ef1ff5fe1dc",
        "fromColumn": "hora_olpn",
        "fromTable": "3_11_status_+_olpn",
        "toColumn": "hora",
        "toTable": "dHora"
      },
      {
        "name": "bc64e0bc-5304-a66c-d303-4e3fc17c2eb2",
        "fromColumn": "sep_setor",
        "fromTable": "3_11_status_+_olpn",
        "toColumn": "sep_setor",
        "toTable": "dsep_setor"
      },
      {
        "name": "177479a7-de13-12c0-effc-03c84dc82a9e",
        "fromColumn": "item",
        "fromTable": "2_04_posicoes_ocupadas_e_vazias",
        "toColumn": "item",
        "toTable": "dValores"
      },
      {
        "name": "346b9caa-fe14-76ec-d9f5-a5d133ce19f5",
        "fromColumn": "item",
        "fromTable": "3_11_status_+_olpn",
        "toColumn": "item",
        "toTable": "dValores"
      },
      {
        "name": "c53d1845-2b09-de6d-d660-c269ed3f60e9",
        "fromColumn": "local",
        "fromTable": "2_04_posicoes_ocupadas_e_vazias",
        "toColumn": "local",
        "toTable": "dZona"
      },
      {
        "name": "9b5d4d55-9bdf-b15e-2e4e-fb00606ef31a",
        "fromColumn": "local_picking",
        "fromTable": "3_11_status_+_olpn",
        "toColumn": "local",
        "toTable": "dZona"
      },
      {
        "name": "AutoDetected_985ab517-5415-46cc-8c1d-adea872307a5",
        "fromColumn": "item",
        "fromTable": "1_06_recebimento",
        "toColumn": "item",
        "toTable": "dValores"
      },
      {
        "name": "AutoDetected_abde27b4-f137-4966-b40f-39f47039af51",
        "fromColumn": "user",
        "fromTable": "1_06_recebimento",
        "toColumn": "user",
        "toTable": "dHeadcount"
      },
      {
        "name": "a91155d8-a0da-3a17-0cbc-8148f990edbd",
        "fromColumn": "Hora",
        "fromTable": "1_06_recebimento",
        "toColumn": "hora",
        "toTable": "dHora"
      },
      {
        "name": "3ca7c3e6-35c8-1474-21ee-a30f166513f8",
        "fromColumn": "data",
        "fromTable": "1_06_recebimento",
        "toColumn": "data",
        "toTable": "dCalendario"
      },
      {
        "name": "AutoDetected_c517e0e7-122f-49fb-a2b8-69f513aba367",
        "fromColumn": "niveis",
        "fromTable": "3_11_status_+_olpn",
        "toColumn": "niveis",
        "toTable": "niveis"
      },
      {
        "name": "AutoDetected_550502f2-3b42-4cfb-a437-a838b6fc29a4",
        "fromColumn": "niveis",
        "fromTable": "2_04_posicoes_ocupadas_e_vazias",
        "toColumn": "niveis",
        "toTable": "niveis"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "dZona",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "local",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "408db53c-6c55-46e7-9f78-97e6c88a40dc",
            "sourceColumn": "local",
            "summarizeBy": "none"
          },
          {
            "name": "zona",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "979adbf3-7a08-46cb-bbab-f9b664c1f008",
            "sourceColumn": "zona",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "88d59a67-7eb3-4295-848c-df736406812b",
        "partitions": [
          {
            "name": "dZona",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"655e4398-476f-446a-a5c6-2564bf30ddca\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"655e4398-476f-446a-a5c6-2564bf30ddca\"]}[Data],",
                "    dZona_ = #\"655e4398-476f-446a-a5c6-2564bf30ddca\"{[entity=\"dZona\",version=\"\"]}[Data]",
                "in",
                "    dZona_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dValores",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d880db11-b27a-4614-99a7-500ef44dc8c8",
            "sourceColumn": "item",
            "summarizeBy": "none"
          },
          {
            "name": "setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "876abd68-9781-497b-afe8-4c315a11631e",
            "sourceColumn": "setor",
            "summarizeBy": "none"
          },
          {
            "name": "valor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1f9c93fe-e445-4bbe-a25e-84be8ef9c7ae",
            "sourceColumn": "valor",
            "summarizeBy": "sum"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "6edf28a7-ec4c-43e1-bf33-ea13128eade4",
        "partitions": [
          {
            "name": "dValores",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"655e4398-476f-446a-a5c6-2564bf30ddca\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"655e4398-476f-446a-a5c6-2564bf30ddca\"]}[Data],",
                "    dValores_ = #\"655e4398-476f-446a-a5c6-2564bf30ddca\"{[entity=\"dValores\",version=\"\"]}[Data]",
                "in",
                "    dValores_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dsep_setor",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "sep_setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "575d22fb-8bbe-45e0-b762-a9582cab1692",
            "sourceColumn": "sep_setor",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "0034ba12-b9bc-40ff-8ef4-d121b4ee468b",
        "partitions": [
          {
            "name": "dsep_setor",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"655e4398-476f-446a-a5c6-2564bf30ddca\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"655e4398-476f-446a-a5c6-2564bf30ddca\"]}[Data],",
                "    dsep_setor_ = #\"655e4398-476f-446a-a5c6-2564bf30ddca\"{[entity=\"dsep_setor\",version=\"\"]}[Data]",
                "in",
                "    dsep_setor_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dHora",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "a2277907-19d3-41f6-a578-f838df4f2e41",
            "sourceColumn": "hora",
            "summarizeBy": "none"
          },
          {
            "name": "hora_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a60f3fde-45cb-44c0-9ae1-bf3c9339c4bf",
            "sourceColumn": "hora_num",
            "summarizeBy": "sum"
          },
          {
            "name": "minuto_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4b09bec3-0f7b-4ed3-a6e9-83e667c648f0",
            "sourceColumn": "minuto_num",
            "summarizeBy": "sum"
          },
          {
            "name": "segundo_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "208d2623-02b2-4663-aa12-70b231cdf0f5",
            "sourceColumn": "segundo_num",
            "summarizeBy": "sum"
          },
          {
            "name": "am_pm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69898248-681d-47d7-a884-846e9e528a02",
            "sourceColumn": "am_pm",
            "summarizeBy": "none"
          },
          {
            "name": "turno",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1691539b-d638-4601-bb5a-ef36a4abe66d",
            "sourceColumn": "turno",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "b670a6dd-c5dd-49a5-bdc0-f9639cf9e45f",
        "partitions": [
          {
            "name": "dHora",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"655e4398-476f-446a-a5c6-2564bf30ddca\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"655e4398-476f-446a-a5c6-2564bf30ddca\"]}[Data],",
                "    dHora_ = #\"655e4398-476f-446a-a5c6-2564bf30ddca\"{[entity=\"dHora\",version=\"\"]}[Data]",
                "in",
                "    dHora_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dHeadcount",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73bc464a-a6ec-43fa-bc2b-1aea4ed98531",
            "sourceColumn": "nome",
            "summarizeBy": "none"
          },
          {
            "name": "funcao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e30981dc-c8f3-4647-9673-1a0a8abaad6c",
            "sourceColumn": "funcao",
            "summarizeBy": "none"
          },
          {
            "name": "chefia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ffecedae-f0ac-48a0-bab4-bdbae44b62aa",
            "sourceColumn": "chefia",
            "summarizeBy": "none"
          },
          {
            "name": "user",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dace4df0-74c7-45b0-ae20-2f385d8a55e8",
            "sourceColumn": "user",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "a5fc25f6-e841-4572-9702-cb3bb952363a",
        "partitions": [
          {
            "name": "dHeadcount",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"655e4398-476f-446a-a5c6-2564bf30ddca\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"655e4398-476f-446a-a5c6-2564bf30ddca\"]}[Data],",
                "    dHeadcount_ = #\"655e4398-476f-446a-a5c6-2564bf30ddca\"{[entity=\"dHeadcount\",version=\"\"]}[Data]",
                "in",
                "    dHeadcount_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCalendario",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yy",
            "lineageTag": "1131a309-9088-4829-855f-a5e3eed21885",
            "sourceColumn": "data",
            "summarizeBy": "none"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "59d921c9-ec55-4f24-86e0-c13c0b69c1d6",
            "sourceColumn": "Ano",
            "summarizeBy": "sum"
          },
          {
            "name": "Nome do mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a705216-8eeb-4a87-b513-2c6794d698ae",
            "sortByColumn": "Mês",
            "sourceColumn": "Nome do mês",
            "summarizeBy": "none"
          },
          {
            "name": "Semana do mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "e05dc655-3410-4065-94bc-f00c9b4f2872",
            "sourceColumn": "Semana do mês",
            "summarizeBy": "sum"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "8c588ffd-d574-45e4-bc1d-087f9f54f263",
            "sourceColumn": "Dia",
            "summarizeBy": "sum"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ed082d18-a632-4483-8348-ef253b7cf041",
            "sourceColumn": "Mês",
            "summarizeBy": "sum"
          },
          {
            "name": "Nome do dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b004cb3b-ff33-4426-8f34-e711207f42ea",
            "sourceColumn": "Nome do dia",
            "summarizeBy": "none"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "94caf742-7a1f-480b-84d0-c8ad32f64887",
            "sourceColumn": "Trimestre",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "def5f655-ff6f-4bc6-8929-e2f45b6693e2",
        "partitions": [
          {
            "name": "dCalendario",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"655e4398-476f-446a-a5c6-2564bf30ddca\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"655e4398-476f-446a-a5c6-2564bf30ddca\"]}[Data],",
                "    dCalendario_ = #\"655e4398-476f-446a-a5c6-2564bf30ddca\"{[entity=\"dCalendario\",version=\"\"]}[Data]",
                "in",
                "    dCalendario_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dBox",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "box",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b63f9e47-15a7-4d32-b6ae-3f6725bc443e",
            "sourceColumn": "box",
            "summarizeBy": "none"
          },
          {
            "name": "porta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fdc62966-a274-44c1-878c-8e2787dd673e",
            "sourceColumn": "porta",
            "summarizeBy": "none"
          },
          {
            "name": "setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ead011a3-c132-49cd-945f-4cd6375202e2",
            "sourceColumn": "setor",
            "summarizeBy": "none"
          },
          {
            "name": "desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fbcc13b8-7b7d-47cb-a71b-b81697f3a094",
            "sourceColumn": "desc",
            "summarizeBy": "none"
          },
          {
            "name": "cubage_m3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "817f9178-0fac-4b89-9854-204280dd5e54",
            "sourceColumn": "cubage_m3",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "65aecf3c-6855-457f-9d26-be4b22ae5d36",
        "partitions": [
          {
            "name": "dBox",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"655e4398-476f-446a-a5c6-2564bf30ddca\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"655e4398-476f-446a-a5c6-2564bf30ddca\"]}[Data],",
                "    dBox_ = #\"655e4398-476f-446a-a5c6-2564bf30ddca\"{[entity=\"dBox\",version=\"\"]}[Data]",
                "in",
                "    dBox_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "3_11_status_+_olpn",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "tipo_pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "611e61ed-f2ae-447c-8e9b-92be41433745",
            "sourceColumn": "tipo_pedido",
            "summarizeBy": "none"
          },
          {
            "name": "wave",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f42298a1-bb02-43b7-8376-9a1c59abd93a",
            "sourceColumn": "wave",
            "summarizeBy": "none"
          },
          {
            "name": "shipment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "68d95f58-ef83-44d1-b57e-c5c2de4ad78d",
            "sourceColumn": "shipment",
            "summarizeBy": "sum"
          },
          {
            "name": "pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b305cee4-b510-49c5-981c-a984a51ab826",
            "sourceColumn": "pedido",
            "summarizeBy": "sum"
          },
          {
            "name": "pedido_venda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8d9eed7-5689-4a03-9807-de84722afeca",
            "sourceColumn": "pedido_venda",
            "summarizeBy": "none"
          },
          {
            "name": "olpn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9e5001e3-e294-4b9e-a8b0-a245a0faf05e",
            "sourceColumn": "olpn",
            "summarizeBy": "sum"
          },
          {
            "name": "data_olpn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "85bf6927-aeed-4b4f-950b-f303a76513a4",
            "sourceColumn": "data_olpn",
            "summarizeBy": "none"
          },
          {
            "name": "tote",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3121e66-0d69-4e17-907f-b45db26af84e",
            "sourceColumn": "tote",
            "summarizeBy": "none"
          },
          {
            "name": "tarefa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ea84ae5-9e12-4aa6-8bd1-1132fdb82155",
            "sourceColumn": "tarefa",
            "summarizeBy": "none"
          },
          {
            "name": "tarefa_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f8afa1a-4d99-49d2-9d07-c2645ed96d7e",
            "sourceColumn": "tarefa_status",
            "summarizeBy": "none"
          },
          {
            "name": "grupo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8807b67c-88b9-406d-a1a9-7cd72a343fe9",
            "sourceColumn": "grupo",
            "summarizeBy": "none"
          },
          {
            "name": "item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "62759f43-927c-4574-9fe1-e815624d22f2",
            "sourceColumn": "item",
            "summarizeBy": "none"
          },
          {
            "name": "desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d90c0c8-b7cb-44ea-8de8-6b3eafd75412",
            "sourceColumn": "desc",
            "summarizeBy": "none"
          },
          {
            "name": "local_picking",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "300cbdcf-a4bf-4810-b453-2e96055abdb3",
            "sourceColumn": "local_picking",
            "summarizeBy": "none"
          },
          {
            "name": "qt_pecas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ba0170a6-a159-4e45-9383-9eabe6f1a235",
            "sourceColumn": "qt_pecas",
            "summarizeBy": "sum"
          },
          {
            "name": "vol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d8f7d06b-740c-4ee5-90df-9b9632a75b6a",
            "sourceColumn": "vol",
            "summarizeBy": "sum"
          },
          {
            "name": "status_olpn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ded35164-aff9-4e39-be7a-82627cf5a6b5",
            "sourceColumn": "status_olpn",
            "summarizeBy": "none"
          },
          {
            "name": "box",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7ff5f28a-2b85-476d-8a89-d64849376af4",
            "sourceColumn": "box",
            "summarizeBy": "none"
          },
          {
            "name": "desc_setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fce8b553-06c5-44ae-beed-2529d5b06749",
            "sourceColumn": "desc_setor",
            "summarizeBy": "none"
          },
          {
            "name": "hora_olpn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "856b08e1-b743-4347-8748-119a00906b74",
            "sourceColumn": "hora_olpn",
            "summarizeBy": "none"
          },
          {
            "name": "sep_setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48de745c-d3cc-4e9f-8e64-e2199db7da81",
            "sourceColumn": "sep_setor",
            "summarizeBy": "none"
          },
          {
            "name": "galpao_or_par",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f26dd955-f027-4ad5-9973-ce2d6638c6e8",
            "sourceColumn": "galpao_or_par",
            "summarizeBy": "none"
          },
          {
            "name": "tipo_expedicao_aba",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6190130-8121-4085-afda-f69624be5d62",
            "sourceColumn": "tipo_expedicao_aba",
            "summarizeBy": "none"
          },
          {
            "name": "valor_unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "27b4458d-c5f3-490d-a96e-6119f9c651a7",
            "sourceColumn": "valor_unit",
            "summarizeBy": "sum"
          },
          {
            "name": "valor_monetario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7abc6ccb-b072-4c88-bd8d-0a98f3fdcd18",
            "sourceColumn": "valor_monetario",
            "summarizeBy": "sum"
          },
          {
            "name": "niveis",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "930963ab-84af-4ae2-bf4f-b3d8728172a6",
            "sourceColumn": "niveis",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1a151689-c168-4b90-9725-0ca7b78ed69d",
        "partitions": [
          {
            "name": "3_11_status_+_olpn",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"3d9d1ebe-412a-42c5-9403-3eae88e767a8\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"3d9d1ebe-412a-42c5-9403-3eae88e767a8\"]}[Data],",
                "    #\"3_11_status_+_olpn_\" = #\"3d9d1ebe-412a-42c5-9403-3eae88e767a8\"{[entity=\"3_11_status_+_olpn\",version=\"\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"3_11_status_+_olpn_\",{{\"data_olpn\", type datetime}}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Tipo Alterado\", each [data_olpn] >= RangeStart and [data_olpn] < RangeEnd)",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          }
        ],
        "refreshPolicy": {
          "incrementalGranularity": "month",
          "incrementalPeriods": 3,
          "incrementalPeriodsOffset": -1,
          "policyType": "basic",
          "pollingExpression": "let Maxdata_olpn = List.Max(#\"3_11_status_+_olpn\"[data_olpn]), accountForNull = if Maxdata_olpn = null then #datetime(1901, 01, 01, 00, 00, 00) else Maxdata_olpn in accountForNull",
          "rollingWindowGranularity": "year",
          "rollingWindowPeriods": 1,
          "sourceExpression": [
            "let",
            "    Fonte = PowerPlatform.Dataflows(null),",
            "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
            "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
            "    #\"3d9d1ebe-412a-42c5-9403-3eae88e767a8\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"3d9d1ebe-412a-42c5-9403-3eae88e767a8\"]}[Data],",
            "    #\"3_11_status_+_olpn_\" = #\"3d9d1ebe-412a-42c5-9403-3eae88e767a8\"{[entity=\"3_11_status_+_olpn\",version=\"\"]}[Data],",
            "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"3_11_status_+_olpn_\",{{\"data_olpn\", type datetime}}),",
            "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Tipo Alterado\", each [data_olpn] >= RangeStart and [data_olpn] < RangeEnd)",
            "in",
            "    #\"Linhas Filtradas\""
          ]
        }
      },
      {
        "name": "2_04_posicoes_ocupadas_e_vazias",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "local",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "950502b6-4ebc-4a7a-9d2a-f337d702d6e1",
            "sourceColumn": "local",
            "summarizeBy": "none"
          },
          {
            "name": "tipo_local",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9af8fa7a-82f9-4eef-83ed-3b4556a6a386",
            "sourceColumn": "tipo_local",
            "summarizeBy": "none"
          },
          {
            "name": "ocupada_ou_vazia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57bf4e1a-1447-4f9e-8967-54b5ab42b1ca",
            "sourceColumn": "ocupada_ou_vazia",
            "summarizeBy": "none"
          },
          {
            "name": "item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5bcb6c3d-3e95-4bf8-867a-321eb147444c",
            "sourceColumn": "item",
            "summarizeBy": "none"
          },
          {
            "name": "desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c5b0895-e961-4dcd-b44f-cd35db5f6de4",
            "sourceColumn": "desc",
            "summarizeBy": "none"
          },
          {
            "name": "qtd_pecas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2f6fa063-8b8b-4904-90a7-ac108c9236d2",
            "sourceColumn": "qtd_pecas",
            "summarizeBy": "sum"
          },
          {
            "name": "tipo_equip",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c5e5786-1197-46ea-92e2-a6113e1e3c25",
            "sourceColumn": "tipo_equip",
            "summarizeBy": "none"
          },
          {
            "name": "boa_ou_sld",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dac600c8-d8bb-4604-bbce-e60e33929d07",
            "sourceColumn": "boa_ou_sld",
            "summarizeBy": "none"
          },
          {
            "name": "desc_setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65e7ba3a-8c1c-4397-8401-519dae69d4e0",
            "sourceColumn": "desc_setor",
            "summarizeBy": "none"
          },
          {
            "name": "desc_marca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ceaca291-6702-4beb-82be-407c8d881470",
            "sourceColumn": "desc_marca",
            "summarizeBy": "none"
          },
          {
            "name": "vol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ad287183-0ba2-4586-8cfc-414466b5fb82",
            "sourceColumn": "vol",
            "summarizeBy": "sum"
          },
          {
            "name": "hab",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d04047ca-76c3-422c-a13d-004df58359f8",
            "sourceColumn": "hab",
            "summarizeBy": "none"
          },
          {
            "name": "valor_monetario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2b18bf82-0a23-42e9-a78c-b628ac82144d",
            "sourceColumn": "valor_monetario",
            "summarizeBy": "sum"
          },
          {
            "name": "niveis",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0847533e-f7a9-4e37-80ae-3725dac5d63d",
            "sourceColumn": "niveis",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bab55116-2cb5-45bb-a603-8eae19921320",
        "partitions": [
          {
            "name": "2_04_posicoes_ocupadas_e_vazias",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"2ea4eec2-7a75-47a9-aedf-93ed32cf21f0\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"2ea4eec2-7a75-47a9-aedf-93ed32cf21f0\"]}[Data],",
                "    #\"2_04_posicoes_ocupadas_e_vazias_\" = #\"2ea4eec2-7a75-47a9-aedf-93ed32cf21f0\"{[entity=\"2_04_posicoes_ocupadas_e_vazias\",version=\"\"]}[Data]",
                "in",
                "    #\"2_04_posicoes_ocupadas_e_vazias_\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Coluna 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9f29b858-0e98-40aa-b19e-6a80d021fc22",
            "sourceColumn": "Coluna 1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "314b4eb1-7ab6-4f94-908d-f1e0b2274614",
        "measures": [
          {
            "name": "qt_pc_zona",
            "displayFolder": "Quantidades",
            "expression": [
              "",
              "",
              "VAR A = SUM('2_04_posicoes_ocupadas_e_vazias'[qtd_pecas])",
              "",
              "RETURN A"
            ],
            "formatString": "0",
            "lineageTag": "67f9a172-7fec-4b1b-9f98-9f5f7b8ae4d2"
          },
          {
            "name": "nome_usuario_logado",
            "displayFolder": "Outros",
            "expression": [
              "",
              "",
              "VAR UsuarioCompleto = USERPRINCIPALNAME()",
              "VAR UsuarioSemDominio = LEFT(UsuarioCompleto, SEARCH(\"@\", UsuarioCompleto, 1) - 1)",
              "VAR UsuarioComEspacos = SUBSTITUTE(UsuarioSemDominio, \".\", \" \")",
              "",
              "VAR PalavrasSeparadas = SUBSTITUTE(UsuarioComEspacos, \" \", \"|\")",
              "VAR ListaPalavras = ",
              "    ADDCOLUMNS(",
              "        GENERATESERIES(1, PATHLENGTH(PalavrasSeparadas)),",
              "        \"Palavra\", PATHITEM(PalavrasSeparadas, [Value])",
              "    )",
              "VAR NomeCapitalizado = ",
              "    CONCATENATEX(",
              "        ListaPalavras,",
              "        UPPER(LEFT([Palavra], 1)) & LOWER(MID([Palavra], 2, LEN([Palavra]))),",
              "        \" \"",
              "    )",
              "RETURN NomeCapitalizado"
            ],
            "lineageTag": "629e7afd-f2be-4497-86ac-85937ab2c7c9"
          },
          {
            "name": "calendario_dinamico",
            "displayFolder": "Calendário dinâmico",
            "expression": [
              "",
              "",
              "VAR B = SUM('3_11_status_+_olpn'[qt_pecas])",
              "",
              "",
              "VAR E = B",
              "",
              "RETURN E",
              ""
            ],
            "formatString": "0",
            "lineageTag": "fe8c1168-3d92-4347-8eae-e02b439696c4"
          },
          {
            "name": "data_hora",
            "displayFolder": "Calendário dinâmico",
            "expression": [
              "",
              "",
              "SELECTEDVALUE(dHora_agora[data])&\" \"&SELECTEDVALUE(dHora_agora[hora])"
            ],
            "lineageTag": "694e9b69-cf53-45a1-bc0a-8aa86b4dc510"
          },
          {
            "name": "%_ocupacao_de_zona",
            "displayFolder": "Locais",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(COUNT('2_04_posicoes_ocupadas_e_vazias'[ocupada_ou_vazia]),",
              "'2_04_posicoes_ocupadas_e_vazias'[ocupada_ou_vazia] = \"Ocupada\")",
              "",
              "VAR B = ",
              "CALCULATE(COUNT('2_04_posicoes_ocupadas_e_vazias'[ocupada_ou_vazia]),",
              "'2_04_posicoes_ocupadas_e_vazias'[ocupada_ou_vazia] = \"Vazia\")",
              "",
              "VAR C =",
              "A/(A+B)",
              "",
              "RETURN",
              "C"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "094da141-d40e-4ff3-ae5c-01c0ede5281f"
          },
          {
            "name": "locais_vazios",
            "displayFolder": "Locais",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              "    COUNT('2_04_posicoes_ocupadas_e_vazias'[ocupada_ou_vazia]),",
              "    '2_04_posicoes_ocupadas_e_vazias'[ocupada_ou_vazia] = \"Vazia\")",
              "",
              "RETURN",
              "A"
            ],
            "formatString": "#,0",
            "lineageTag": "c3ebe011-ab20-495a-b8a7-bb657995aabe"
          },
          {
            "name": "locais_ocupados",
            "displayFolder": "Locais",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              "    COUNT('2_04_posicoes_ocupadas_e_vazias'[ocupada_ou_vazia]),",
              "    '2_04_posicoes_ocupadas_e_vazias'[ocupada_ou_vazia] = \"Ocupada\")",
              "",
              "RETURN",
              "A"
            ],
            "formatString": "#,0",
            "lineageTag": "4d4a375d-7788-4f7e-a0c1-cd9d05bb57d9"
          },
          {
            "name": "locais_n_definidos",
            "displayFolder": "Locais",
            "expression": [
              "",
              "VAR A =",
              "CALCULATE(",
              "    COUNT('2_04_posicoes_ocupadas_e_vazias'[boa_ou_sld]),",
              "    '2_04_posicoes_ocupadas_e_vazias'[boa_ou_sld] = BLANK())",
              "RETURN",
              "A"
            ],
            "formatString": "#,0",
            "lineageTag": "ade1dc6c-e1b6-4fd1-9cd5-ce7d9274087c"
          },
          {
            "name": "locais_boa",
            "displayFolder": "Locais",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              "    COUNT('2_04_posicoes_ocupadas_e_vazias'[boa_ou_sld]),",
              "    '2_04_posicoes_ocupadas_e_vazias'[boa_ou_sld] = \"BOA\")",
              "",
              "RETURN",
              "A"
            ],
            "formatString": "#,0",
            "lineageTag": "c5c77ef3-db6d-4d8b-9d36-f9a39b62e754"
          },
          {
            "name": "locais_sld",
            "displayFolder": "Locais",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              "    COUNT('2_04_posicoes_ocupadas_e_vazias'[boa_ou_sld]),",
              "    '2_04_posicoes_ocupadas_e_vazias'[boa_ou_sld] = \"SLD\")",
              "",
              "RETURN",
              "A"
            ],
            "formatString": "#,0",
            "lineageTag": "21609817-a7f8-4e91-a9f8-e7c90f8de27e"
          },
          {
            "name": "locais_qeb",
            "displayFolder": "Locais",
            "expression": [
              "",
              "VAR A =",
              "CALCULATE(",
              "    COUNT('2_04_posicoes_ocupadas_e_vazias'[boa_ou_sld]),",
              "    '2_04_posicoes_ocupadas_e_vazias'[boa_ou_sld] = \"QEB\")",
              "RETURN",
              "A"
            ],
            "formatString": "#,0",
            "lineageTag": "3d08babb-aa82-4135-88d5-9681e9e97a98"
          },
          {
            "name": "locais_reserva",
            "displayFolder": "Locais",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "    COUNT('2_04_posicoes_ocupadas_e_vazias'[tipo_local]),",
              "    '2_04_posicoes_ocupadas_e_vazias'[tipo_local] = \"RESERVA\")",
              "",
              "RETURN",
              "A"
            ],
            "formatString": "#,0",
            "lineageTag": "e3b2c52d-0c84-49a3-9cbd-b4a47faae20a"
          },
          {
            "name": "locais_coleta",
            "displayFolder": "Locais",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "    COUNT('2_04_posicoes_ocupadas_e_vazias'[tipo_local]),",
              "    '2_04_posicoes_ocupadas_e_vazias'[tipo_local] = \"POSIÇÕES DE PICKING\")",
              "",
              "RETURN",
              "A"
            ],
            "formatString": "#,0",
            "lineageTag": "728489ff-1592-4be2-9559-36811b02a365"
          },
          {
            "name": "pcs_armazenadas",
            "displayFolder": "Quantidades",
            "expression": [
              "",
              "",
              "SUM('2_04_posicoes_ocupadas_e_vazias'[qtd_pecas])"
            ],
            "formatString": "#,0",
            "lineageTag": "770b3735-eb7a-432b-a729-8aeef1223d74"
          },
          {
            "name": "valor_armazem",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "displayFolder": "R$ Valor",
            "expression": [
              "",
              "",
              "SUM('2_04_posicoes_ocupadas_e_vazias'[valor_monetario])"
            ],
            "formatString": "\"R$\"#,0.00;-\"R$\"#,0.00;\"R$\"#,0.00",
            "lineageTag": "2067db4e-7ded-4a0e-a375-21e2e8607190"
          },
          {
            "name": "qtd_em_movimento",
            "displayFolder": "Quantidades",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              " SUM('3_11_status_+_olpn'[qt_pecas]),",
              " '3_11_status_+_olpn'[status_olpn] <> \"Shipped\",",
              " dCalendario[data] = TODAY())",
              "",
              "RETURN",
              "A"
            ],
            "formatString": "#,0",
            "lineageTag": "a8f271fe-fa55-4d40-ba79-a0784c8cb1ff"
          },
          {
            "name": "valor_em_movimento",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "displayFolder": "R$ Valor",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              " SUM('3_11_status_+_olpn'[valor_monetario]),",
              " '3_11_status_+_olpn'[status_olpn] <> \"Shipped\",",
              " dCalendario[data] = TODAY())",
              "",
              "RETURN",
              "A"
            ],
            "formatString": "\"R$\"#,0.00;-\"R$\"#,0.00;\"R$\"#,0.00",
            "lineageTag": "ac8e6537-103b-40ad-be5e-4c73e9db79a2"
          },
          {
            "name": "qtd_em_recebimento",
            "displayFolder": "Quantidades",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              " SUM('1_06_recebimento'[qtd_Recebida]),",
              " '1_06_recebimento'[status] = \"8000-Verified\",",
              " dCalendario[data] = TODAY())",
              "",
              "RETURN",
              "A"
            ],
            "formatString": "#,0",
            "lineageTag": "7d052c24-4020-421a-bc25-538ab36e1779"
          },
          {
            "name": "valor_em_recebimento",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "displayFolder": "R$ Valor",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              " SUM('1_06_recebimento'[valor_monetario]),",
              " '1_06_recebimento'[status] = \"8000-Verified\",",
              " dCalendario[data] = TODAY())",
              "",
              "RETURN",
              "A"
            ],
            "formatString": "\"R$\"#,0.00;-\"R$\"#,0.00;\"R$\"#,0.00",
            "lineageTag": "3800ef53-f3c6-479f-aa6f-758aec229648"
          },
          {
            "name": "qt_pecas_olpn",
            "displayFolder": "Quantidades",
            "expression": [
              "",
              "",
              "SUM('3_11_status_+_olpn'[qt_pecas])"
            ],
            "formatString": "#,0",
            "lineageTag": "09ca7d61-1454-46fb-89e5-f4a770a36ec0"
          },
          {
            "name": "qt_saida",
            "displayFolder": "Curva ABC",
            "expression": [
              "",
              "SUM('3_11_status_+_olpn'[qt_pecas])"
            ],
            "formatString": "#,0",
            "lineageTag": "79700a15-d903-4c43-a204-3752e16b7a06"
          },
          {
            "name": "saida_acumulada",
            "displayFolder": "Curva ABC",
            "expression": [
              "",
              "",
              "VAR saida = [qt_saida]",
              "",
              "VAR saida_acumulada = ",
              "CALCULATE(",
              "    [qt_saida],",
              "    FILTER(",
              "        ALL('3_11_status_+_olpn'[desc_setor]),",
              "        [qt_saida] >= saida))",
              "",
              "RETURN saida_acumulada"
            ],
            "formatString": "0",
            "lineageTag": "4ad51e7a-ea02-4651-93fa-398a767ff5f3"
          },
          {
            "name": "%_saida",
            "displayFolder": "Curva ABC",
            "expression": [
              "",
              "",
              "VAR saida_total = ",
              "CALCULATE(",
              "    [qt_saida], ALL('3_11_status_+_olpn'[desc_setor]))",
              "",
              "RETURN",
              "DIVIDE([saida_acumulada], saida_total)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "1660afcf-a9b1-4b6a-86eb-b2324bb93196"
          },
          {
            "name": "pareto_70",
            "displayFolder": "Curva ABC",
            "expression": [
              "",
              "",
              "IF(",
              "    [%_saida_item] <= 0.7, \"#151B9E\", \"#8E98FF\"",
              ")"
            ],
            "lineageTag": "e1c0fd7d-a9b9-424c-9277-8d1bc29ab2ed"
          },
          {
            "name": "saida_70",
            "displayFolder": "Curva ABC",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [qt_saida],",
              "    FILTER(",
              "        ALLSELECTED('3_11_status_+_olpn'[desc_setor]),",
              "        [curva_ABC] = \"Curva A\"))",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "bfb7586b-db6b-4463-a476-46276c564baf"
          },
          {
            "name": "curva_ABC",
            "displayFolder": "Curva ABC",
            "expression": [
              "",
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [%_saida] <= 0.7 ,\"Curva A\",",
              "    [%_saida] <= 0.9 ,\"Curva B\", \"Curva C\")"
            ],
            "lineageTag": "147a082c-e5de-4faf-95e2-da2273863941"
          },
          {
            "name": "saida_20",
            "displayFolder": "Curva ABC",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [qt_saida],",
              "    FILTER(",
              "        ALLSELECTED('3_11_status_+_olpn'[desc_setor]),",
              "        [curva_ABC] = \"Curva B\" ))"
            ],
            "formatString": "#,0",
            "lineageTag": "184de24c-c296-4e92-b2fe-eebe1daa349e"
          },
          {
            "name": "saida_10",
            "displayFolder": "Curva ABC",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [qt_saida],",
              "    FILTER(",
              "        ALLSELECTED('3_11_status_+_olpn'[desc_setor]),",
              "        [curva_ABC] = \"Curva C\"))"
            ],
            "formatString": "#,0",
            "lineageTag": "f584459f-36d0-477b-86ad-4442ad034b52"
          },
          {
            "name": "curva_a",
            "displayFolder": "Curva ABC",
            "expression": [
              "",
              "",
              "VAR A =",
              "COUNTROWS(",
              "    FILTER(",
              "        ALLSELECTED('3_11_status_+_olpn'[desc_setor]),",
              "        [curva_ABC] = \"Curva A\"))",
              "",
              "VAR B =",
              "",
              "COUNTROWS(",
              "    FILTER(",
              "        ALLSELECTED('3_11_status_+_olpn'[desc_setor]),",
              "        [curva_ABC] = \"Curva B\" || [curva_ABC] = \"Curva C\" || [curva_ABC] = \"Curva A\"))",
              "",
              "VAR C =",
              "A/B",
              "",
              "RETURN",
              "C"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "4a2cf5bb-64dc-4e94-a68a-39c94786c361"
          },
          {
            "name": "curva_b",
            "displayFolder": "Curva ABC",
            "expression": [
              "",
              "",
              "VAR A =",
              "COUNTROWS(",
              "    FILTER(",
              "        ALLSELECTED('3_11_status_+_olpn'[desc_setor]),",
              "        [curva_ABC] = \"Curva B\"))",
              "",
              "VAR B =",
              "",
              "COUNTROWS(",
              "    FILTER(",
              "        ALLSELECTED('3_11_status_+_olpn'[desc_setor]),",
              "        [curva_ABC] = \"Curva B\" || [curva_ABC] = \"Curva C\" || [curva_ABC] = \"Curva A\"))",
              "",
              "VAR C =",
              "A/B",
              "",
              "RETURN",
              "c"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "be743418-261c-4f59-a772-8beb872b96d0"
          },
          {
            "name": "curva_c",
            "displayFolder": "Curva ABC",
            "expression": [
              "",
              "",
              "VAR A =",
              "COUNTROWS(",
              "    FILTER(",
              "        ALLSELECTED('3_11_status_+_olpn'[desc_setor]),",
              "        [curva_ABC] = \"Curva C\"))",
              "",
              "VAR B =",
              "",
              "COUNTROWS(",
              "    FILTER(",
              "        ALLSELECTED('3_11_status_+_olpn'[desc_setor]),",
              "        [curva_ABC] = \"Curva B\" || [curva_ABC] = \"Curva C\" || [curva_ABC] = \"Curva A\"))",
              "",
              "VAR C =",
              "A/B",
              "",
              "RETURN",
              "c"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "0d8fd295-8d97-4f93-9111-b7c920ddf6eb"
          },
          {
            "name": "curva_a_tratada",
            "displayFolder": "Curva ABC",
            "expression": "FORMAT([curva_a],\"0%\")&\" \"&\"dos SKU's expedidos\"",
            "lineageTag": "4597a7c7-15bc-4f6c-a753-26b9df972f4a"
          },
          {
            "name": "curva_b_tratada",
            "displayFolder": "Curva ABC",
            "expression": "FORMAT([curva_b],\"0%\")&\" \"&\"dos SKU's expedidos\"",
            "lineageTag": "76f258d5-207b-4d38-9501-938886f494f4"
          },
          {
            "name": "curva_c_tratada",
            "displayFolder": "Curva ABC",
            "expression": "FORMAT([curva_c],\"0%\")&\" \"&\"dos SKU's expedidos\"",
            "lineageTag": "ff4a6a75-7a78-4958-ac3b-53dd487eb8aa"
          },
          {
            "name": "filterABC",
            "displayFolder": "Curva ABC",
            "expression": [
              "",
              "",
              "IF(SELECTEDVALUE(auxCurva[curva]) = [curva_ABC], 1,0)"
            ],
            "formatString": "0",
            "lineageTag": "f0fc745a-8448-459f-a84d-5ab8a8f79898"
          },
          {
            "name": "%_saida_item",
            "displayFolder": "Curva ABC",
            "expression": [
              "",
              "",
              "VAR saida_total = ",
              "CALCULATE(",
              "    [qt_saida], ALL('3_11_status_+_olpn'[desc]))",
              "",
              "RETURN",
              "DIVIDE([saida_acumulada_item], saida_total)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "25945a1d-9882-4aae-a521-6806cb1dd88a"
          },
          {
            "name": "saida_acumulada_item",
            "displayFolder": "Curva ABC",
            "expression": [
              "",
              "",
              "VAR saida = [qt_saida]",
              "",
              "VAR saida_acumulada = ",
              "CALCULATE(",
              "    [qt_saida],",
              "    FILTER(",
              "        ALL('3_11_status_+_olpn'[desc]),",
              "        [qt_saida] >= saida))",
              "",
              "RETURN saida_acumulada"
            ],
            "formatString": "0",
            "lineageTag": "acf5367f-48ca-4b99-9236-d7aea02bd1bc"
          },
          {
            "name": "curva_ABC_item",
            "displayFolder": "Curva ABC",
            "expression": [
              "",
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [%_saida_item] <= 0.7 ,\"Curva A\",",
              "    [%_saida_item] <= 0.9 ,\"Curva B\", \"Curva C\")"
            ],
            "lineageTag": "cdd58972-8b22-478a-ad01-97778accf9a6"
          },
          {
            "name": "saida_hoje",
            "displayFolder": "Outros",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    SUM('3_11_status_+_olpn'[qt_pecas]),",
              "    '3_11_status_+_olpn'[status_olpn] <> \"Shipped\",",
              "    dCalendario[data] = TODAY())"
            ],
            "formatString": "#,0",
            "lineageTag": "97fd2c82-dbc1-4a4c-beef-83d8fe3f9b06"
          },
          {
            "name": "%_de_saida_por_zona",
            "displayFolder": "Outros",
            "expression": [
              "",
              "",
              "VAR A = ",
              "",
              "CALCULATE(",
              "    [saida_hoje],",
              "    ALLSELECTED(dZona[zona]))",
              "",
              "VAR B = [saida_hoje]",
              "",
              "VAR C = DIVIDE(B,A)",
              "",
              "RETURN",
              "C"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "553a16a3-6276-499c-ad9a-88bd12f8114f"
          },
          {
            "name": "nivel_saida_1",
            "displayFolder": "Outros",
            "expression": [
              "",
              "",
              "VAR A = ",
              "",
              "CALCULATE(",
              "    SUM('3_11_status_+_olpn'[qt_pecas]),",
              "    '3_11_status_+_olpn'[niveis] = \"Nível 1\")",
              "",
              "VAR B = ",
              "",
              "CALCULATE(",
              "    SUM('3_11_status_+_olpn'[qt_pecas]),",
              "    '3_11_status_+_olpn'[niveis] = \"Nível Alto\")",
              "",
              "VAR C = ",
              "DIVIDE(A,(A+B))",
              "",
              "RETURN",
              "C"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "b7b33954-3b58-438c-95a5-cdf791b9ea0b"
          },
          {
            "name": "nivel_saida_alto",
            "displayFolder": "Outros",
            "expression": [
              "",
              "",
              "VAR A = ",
              "",
              "CALCULATE(",
              "    SUM('3_11_status_+_olpn'[qt_pecas]),",
              "    '3_11_status_+_olpn'[niveis] = \"Nível 1\")",
              "",
              "VAR B = ",
              "",
              "CALCULATE(",
              "    SUM('3_11_status_+_olpn'[qt_pecas]),",
              "    '3_11_status_+_olpn'[niveis] = \"Nível Alto\")",
              "",
              "VAR C = ",
              "DIVIDE(B,(A+B))",
              "",
              "RETURN",
              "C"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "715e12c7-f7ab-459c-b6d5-171ec7ee9000"
          }
        ],
        "partitions": [
          {
            "name": "Medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "1_06_recebimento",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e189e37-bd46-477b-9790-fc96aa23b24c",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "boa_ou_sld",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "caa1f3c6-c3b2-4d43-954d-435ab05320cf",
            "sourceColumn": "boa_ou_sld",
            "summarizeBy": "none"
          },
          {
            "name": "qtd_Recebida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b7be7f08-5e9a-47ee-b01e-013bf146378c",
            "sourceColumn": "qtd_Recebida",
            "summarizeBy": "sum"
          },
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "ad980933-0c22-4736-8abe-e196897b74e9",
            "sourceColumn": "data",
            "summarizeBy": "none"
          },
          {
            "name": "tipo_recebimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "738e53b1-924d-460d-bce4-f88143bd0dc0",
            "sourceColumn": "tipo_recebimento",
            "summarizeBy": "none"
          },
          {
            "name": "item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4fe32b5b-95ec-4602-9331-539cc646f984",
            "sourceColumn": "item",
            "summarizeBy": "none"
          },
          {
            "name": "desc_item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1d7257c-d61a-41cb-ab86-e06c6539e7eb",
            "sourceColumn": "desc_item",
            "summarizeBy": "none"
          },
          {
            "name": "setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1109465f-ea00-494a-a9c3-ca7afc15e55d",
            "sourceColumn": "setor",
            "summarizeBy": "none"
          },
          {
            "name": "marca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2f3ac9a-d4ff-43e7-b7a5-892a1d732bfe",
            "sourceColumn": "marca",
            "summarizeBy": "none"
          },
          {
            "name": "user",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd93d5cf-84cd-4c7c-ab34-a9143d2bf520",
            "sourceColumn": "user",
            "summarizeBy": "none"
          },
          {
            "name": "Hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "c37cbecf-485f-425b-8543-38ed41077642",
            "sourceColumn": "Hora",
            "summarizeBy": "none"
          },
          {
            "name": "valor_unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "66d225fa-201b-4183-8ec0-006e209827d5",
            "sourceColumn": "valor_unit",
            "summarizeBy": "sum"
          },
          {
            "name": "valor_monetario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a543ed7f-8e6b-48d7-a4ae-ab63f00bb40a",
            "sourceColumn": "valor_monetario",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "f3c0cca6-2eed-4272-a817-adf7c8a4681e",
        "partitions": [
          {
            "name": "1_06_recebimento",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"e18e73c0-d79b-42fc-b757-d34719497a4b\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"e18e73c0-d79b-42fc-b757-d34719497a4b\"]}[Data],",
                "    #\"1_06_recebimento_\" = #\"e18e73c0-d79b-42fc-b757-d34719497a4b\"{[entity=\"1_06_recebimento\",version=\"\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"1_06_recebimento_\",{{\"data\", type datetime}}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Tipo Alterado\", each [data] >= RangeStart and [data] < RangeEnd)",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          }
        ],
        "refreshPolicy": {
          "incrementalGranularity": "month",
          "incrementalPeriods": 3,
          "incrementalPeriodsOffset": -1,
          "policyType": "basic",
          "pollingExpression": "let Maxdata = List.Max(#\"1_06_recebimento\"[data]), accountForNull = if Maxdata = null then #datetime(1901, 01, 01, 00, 00, 00) else Maxdata in accountForNull",
          "rollingWindowGranularity": "year",
          "rollingWindowPeriods": 1,
          "sourceExpression": [
            "let",
            "    Fonte = PowerPlatform.Dataflows(null),",
            "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
            "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
            "    #\"e18e73c0-d79b-42fc-b757-d34719497a4b\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"e18e73c0-d79b-42fc-b757-d34719497a4b\"]}[Data],",
            "    #\"1_06_recebimento_\" = #\"e18e73c0-d79b-42fc-b757-d34719497a4b\"{[entity=\"1_06_recebimento\",version=\"\"]}[Data],",
            "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"1_06_recebimento_\",{{\"data\", type datetime}}),",
            "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Tipo Alterado\", each [data] >= RangeStart and [data] < RangeEnd)",
            "in",
            "    #\"Linhas Filtradas\""
          ]
        }
      },
      {
        "name": "niveis",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "niveis",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8c38182-71ce-405a-b3f9-08f9af6d3c6b",
            "sourceColumn": "niveis",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7d4a40be-3b93-4cce-b131-ec81742999d1",
        "partitions": [
          {
            "name": "niveis",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\" = Workspaces{[workspaceId=\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"]}[Data],",
                "    #\"655e4398-476f-446a-a5c6-2564bf30ddca\" = #\"ad52077a-cb57-4d00-bc6c-32a23a7d230e\"{[dataflowId=\"655e4398-476f-446a-a5c6-2564bf30ddca\"]}[Data],",
                "    niveis_ = #\"655e4398-476f-446a-a5c6-2564bf30ddca\"{[entity=\"niveis\",version=\"\"]}[Data]",
                "in",
                "    niveis_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "auxCurva",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "curva",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae7e5e1a-136f-4d31-82ce-e611b74691ed",
            "sourceColumn": "curva",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f15c61df-aa27-4e19-abce-5a077ad39f38",
        "partitions": [
          {
            "name": "auxCurva",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wci4tKktUcFSK1YGxnZDYzkqxsQA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [curva = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"curva\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dHora_agora",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b98b4582-479e-4935-8f18-351e9ca2525e",
            "sourceColumn": "data",
            "summarizeBy": "none"
          },
          {
            "name": "hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "5788ff10-95ef-4fcf-a2dc-3b3e7a6e186f",
            "sourceColumn": "hora",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c83dc280-9256-401d-b75c-6614c7f97e86",
        "partitions": [
          {
            "name": "dHora_agora",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = DateTime.From(DateTime.LocalNow()) - #duration(0, 3, 0, 0),",
                "    #\"Convertido para Tabela\" = #table(1, {{Fonte}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Convertido para Tabela\",{{\"Column1\", \"hora\"}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"hora\", type datetime}}),",
                "  #\"Hora inserida\" = Table.AddColumn(#\"Tipo Alterado\", \"Hora (2)\", each DateTime.Time([hora]), type nullable time),",
                "  #\"Data calculada\" = Table.TransformColumns(#\"Hora inserida\", {{\"hora\", each DateTime.Date(_), type nullable date}}),",
                "  #\"Colunas renomeadas 1\" = Table.RenameColumns(#\"Data calculada\", {{\"hora\", \"data\"}, {\"Hora (2)\", \"hora\"}})",
                "in",
                "    #\"Colunas renomeadas 1\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}